// Mapa de correções de acentos para nomes brasileiros comuns
// Chave: versão sem acento (lowercase), Valor: versão correta com acento

const ACCENT_CORRECTIONS: Record<string, string> = {
  // Nomes próprios femininos
  'adelia': 'Adélia',
  'adriana': 'Adriana',
  'agueda': 'Águeda',
  'alaides': 'Alaídes',
  'amalia': 'Amália',
  'amelia': 'Amélia',
  'ana': 'Ana',
  'andrea': 'Andréa',
  'andreia': 'Andréia',
  'angela': 'Ângela',
  'antonia': 'Antônia',
  'aparecida': 'Aparecida',
  'aurelia': 'Aurélia',
  'beatriz': 'Beatriz',
  'berenice': 'Berenice',
  'cacilda': 'Cacilda',
  'camila': 'Camila',
  'carla': 'Carla',
  'carmem': 'Carmem',
  'catia': 'Cátia',
  'cecilia': 'Cecília',
  'celia': 'Célia',
  'claudia': 'Cláudia',
  'cleide': 'Cleide',
  'cleia': 'Cléia',
  'conceicao': 'Conceição',
  'cristiane': 'Cristiane',
  'dalva': 'Dalva',
  'daniela': 'Daniela',
  'debora': 'Débora',
  'delia': 'Délia',
  'denise': 'Denise',
  'dirce': 'Dirce',
  'edna': 'Edna',
  'edneia': 'Ednéia',
  'elaine': 'Elaine',
  'elena': 'Elena',
  'eliana': 'Eliana',
  'elisangela': 'Elisângela',
  'eloisa': 'Eloísa',
  'emilia': 'Emília',
  'eunice': 'Eunice',
  'eva': 'Eva',
  'fatima': 'Fátima',
  'fernanda': 'Fernanda',
  'flavia': 'Flávia',
  'francisca': 'Francisca',
  'geralda': 'Geralda',
  'gloria': 'Glória',
  'graca': 'Graça',
  'helena': 'Helena',
  'heloisa': 'Heloísa',
  'ilda': 'Ilda',
  'ines': 'Inês',
  'iraci': 'Iraci',
  'irene': 'Irene',
  'iris': 'Íris',
  'isaura': 'Isaura',
  'ivone': 'Ivone',
  'joana': 'Joana',
  'josefa': 'Josefa',
  'julia': 'Júlia',
  'juliana': 'Juliana',
  'juraci': 'Juraci',
  'katia': 'Kátia',
  'lais': 'Laís',
  'larissa': 'Larissa',
  'laura': 'Laura',
  'leda': 'Leda',
  'leia': 'Léia',
  'leticia': 'Letícia',
  'lidia': 'Lídia',
  'ligia': 'Lígia',
  'lilia': 'Lília',
  'liliane': 'Liliane',
  'lucia': 'Lúcia',
  'luciana': 'Luciana',
  'luisa': 'Luísa',
  'luiza': 'Luíza',
  'lurdes': 'Lurdes',
  'madalena': 'Madalena',
  'marcia': 'Márcia',
  'margarete': 'Margarete',
  'margarida': 'Margarida',
  'maria': 'Maria',
  'mariana': 'Mariana',
  'marilene': 'Marilene',
  'marina': 'Marina',
  'marlene': 'Marlene',
  'marta': 'Marta',
  'mercedes': 'Mercedes',
  'miriam': 'Míriam',
  'monica': 'Mônica',
  'nadia': 'Nádia',
  'natalia': 'Natália',
  'neide': 'Neide',
  'nelia': 'Nélia',
  'neuza': 'Neuza',
  'nilza': 'Nilza',
  'noemia': 'Noêmia',
  'odete': 'Odete',
  'olivia': 'Olívia',
  'otilia': 'Otília',
  'pamela': 'Pâmela',
  'patricia': 'Patrícia',
  'paula': 'Paula',
  'priscila': 'Priscila',
  'raquel': 'Raquel',
  'regina': 'Regina',
  'renata': 'Renata',
  'rita': 'Rita',
  'rosa': 'Rosa',
  'rosalia': 'Rosália',
  'rosana': 'Rosana',
  'rosangela': 'Rosângela',
  'roseli': 'Roseli',
  'rosilene': 'Rosilene',
  'ruth': 'Ruth',
  'sandra': 'Sandra',
  'selma': 'Selma',
  'silvia': 'Sílvia',
  'simone': 'Simone',
  'solange': 'Solange',
  'sonia': 'Sônia',
  'soraia': 'Soraia',
  'sueli': 'Sueli',
  'suzana': 'Suzana',
  'tania': 'Tânia',
  'tatiana': 'Tatiana',
  'tereza': 'Tereza',
  'terezinha': 'Terezinha',
  'valeria': 'Valéria',
  'vania': 'Vânia',
  'vera': 'Vera',
  'vilma': 'Vilma',
  'virginia': 'Virgínia',
  'vitoria': 'Vitória',
  'viviane': 'Viviane',
  'zelia': 'Zélia',
  'zenaide': 'Zenaide',
  'zilda': 'Zilda',
  
  // Nomes próprios masculinos
  'abilio': 'Abílio',
  'adao': 'Adão',
  'ademir': 'Ademir',
  'adriano': 'Adriano',
  'afonso': 'Afonso',
  'agostinho': 'Agostinho',
  'airton': 'Airton',
  'alberto': 'Alberto',
  'alcides': 'Alcides',
  'aldo': 'Aldo',
  'alexandre': 'Alexandre',
  'alfredo': 'Alfredo',
  'alvaro': 'Álvaro',
  'amauri': 'Amauri',
  'amilton': 'Amílton',
  'andre': 'André',
  'anisio': 'Anísio',
  'antonio': 'Antônio',
  'aparicio': 'Aparício',
  'aristides': 'Aristides',
  'armando': 'Armando',
  'arnaldo': 'Arnaldo',
  'artur': 'Artur',
  'atilio': 'Atílio',
  'augusto': 'Augusto',
  'aurelio': 'Aurélio',
  'benedito': 'Benedito',
  'bento': 'Bento',
  'bernardo': 'Bernardo',
  'bonifacio': 'Bonifácio',
  'bruno': 'Bruno',
  'caio': 'Caio',
  'candido': 'Cândido',
  'carlos': 'Carlos',
  'cassio': 'Cássio',
  'celso': 'Celso',
  'cesar': 'César',
  'cicero': 'Cícero',
  'claudio': 'Cláudio',
  'cristiano': 'Cristiano',
  'cristovao': 'Cristóvão',
  'damiao': 'Damião',
  'daniel': 'Daniel',
  'darci': 'Darci',
  'dario': 'Dário',
  'david': 'David',
  'decio': 'Décio',
  'demetrio': 'Demétrio',
  'denis': 'Denis',
  'diego': 'Diego',
  'dimas': 'Dimas',
  'diogo': 'Diogo',
  'domingos': 'Domingos',
  'donizete': 'Donizete',
  'dorival': 'Dorival',
  'edgar': 'Edgar',
  'edilson': 'Edilson',
  'edivaldo': 'Edivaldo',
  'edmar': 'Edmar',
  'edmilson': 'Edmílson',
  'edson': 'Edson',
  'eduardo': 'Eduardo',
  'elias': 'Elias',
  'elio': 'Élio',
  'eliseu': 'Eliseu',
  'emerson': 'Emerson',
  'emilio': 'Emílio',
  'enio': 'Ênio',
  'erasmo': 'Erasmo',
  'erico': 'Érico',
  'ernani': 'Ernani',
  'ernesto': 'Ernesto',
  'euclides': 'Euclides',
  'eugenio': 'Eugênio',
  'evaldo': 'Evaldo',
  'evandro': 'Evandro',
  'expedito': 'Expedito',
  'fabiano': 'Fabiano',
  'fabio': 'Fábio',
  'fabricio': 'Fabrício',
  'felicio': 'Felício',
  'felipe': 'Felipe',
  'felix': 'Félix',
  'fernando': 'Fernando',
  'firmino': 'Firmino',
  'flavio': 'Flávio',
  'francisco': 'Francisco',
  'frederico': 'Frederico',
  'geraldo': 'Geraldo',
  'germano': 'Germano',
  'geronimo': 'Gerônimo',
  'gilberto': 'Gilberto',
  'gilmar': 'Gilmar',
  'gilson': 'Gilson',
  'giovani': 'Giovani',
  'glauco': 'Glauco',
  'gregorio': 'Gregório',
  'guilherme': 'Guilherme',
  'gustavo': 'Gustavo',
  'helio': 'Hélio',
  'henrique': 'Henrique',
  'hercules': 'Hércules',
  'humberto': 'Humberto',
  'idalecio': 'Idalécio',
  'ignacio': 'Ignácio',
  'inacio': 'Inácio',
  'isaias': 'Isaías',
  'isidoro': 'Isidoro',
  'ismael': 'Ismael',
  'italo': 'Ítalo',
  'ivan': 'Ivan',
  'ivanildo': 'Ivanildo',
  'jaime': 'Jaime',
  'jair': 'Jair',
  'januario': 'Januário',
  'jefferson': 'Jefferson',
  'jeronimo': 'Jerônimo',
  'joao': 'João',
  'joaquim': 'Joaquim',
  'joel': 'Joel',
  'jonas': 'Jonas',
  'jorge': 'Jorge',
  'jose': 'José',
  'josue': 'Josué',
  'julio': 'Júlio',
  'junior': 'Júnior',
  'lazaro': 'Lázaro',
  'leandro': 'Leandro',
  'leonardo': 'Leonardo',
  'leonel': 'Leonel',
  'leonidas': 'Leônidas',
  'lindomar': 'Lindomar',
  'lourival': 'Lourival',
  'lucas': 'Lucas',
  'luciano': 'Luciano',
  'lucio': 'Lúcio',
  'luis': 'Luís',
  'luiz': 'Luiz',
  'manoel': 'Manoel',
  'manuel': 'Manuel',
  'marcelo': 'Marcelo',
  'marcio': 'Márcio',
  'marco': 'Marco',
  'marcos': 'Marcos',
  'mario': 'Mário',
  'mateus': 'Mateus',
  'matias': 'Matias',
  'mauricio': 'Maurício',
  'mauro': 'Mauro',
  'messias': 'Messias',
  'milton': 'Milton',
  'moacir': 'Moacir',
  'moises': 'Moisés',
  'murilo': 'Murilo',
  'nelio': 'Nélio',
  'nelson': 'Nelson',
  'newton': 'Newton',
  'nicolau': 'Nicolau',
  'nilson': 'Nilson',
  'nilton': 'Nilton',
  'nivaldo': 'Nivaldo',
  'norberto': 'Norberto',
  'odair': 'Odair',
  'olimpio': 'Olímpio',
  'olivio': 'Olívio',
  'orlando': 'Orlando',
  'osmar': 'Osmar',
  'osvaldo': 'Osvaldo',
  'otavio': 'Otávio',
  'ovidio': 'Ovídio',
  'paschoal': 'Paschoal',
  'patricio': 'Patrício',
  'paulo': 'Paulo',
  'pedro': 'Pedro',
  'petronio': 'Petrônio',
  'placido': 'Plácido',
  'plinio': 'Plínio',
  'procopio': 'Procópio',
  'rafael': 'Rafael',
  'raimundo': 'Raimundo',
  'raul': 'Raul',
  'reginaldo': 'Reginaldo',
  'reinaldo': 'Reinaldo',
  'renato': 'Renato',
  'ricardo': 'Ricardo',
  'roberto': 'Roberto',
  'rodolfo': 'Rodolfo',
  'rodrigo': 'Rodrigo',
  'rogerio': 'Rogério',
  'romulo': 'Rômulo',
  'ronaldo': 'Ronaldo',
  'rubens': 'Rubens',
  'salomao': 'Salomão',
  'samuel': 'Samuel',
  'sebastiao': 'Sebastião',
  'sergio': 'Sérgio',
  'sidnei': 'Sidnei',
  'silvio': 'Sílvio',
  'simao': 'Simão',
  'tadeu': 'Tadeu',
  'teodoro': 'Teodoro',
  'teofilo': 'Teófilo',
  'thiago': 'Thiago',
  'tiago': 'Tiago',
  'tobias': 'Tobias',
  'tomas': 'Tomás',
  'tome': 'Tomé',
  'ulisses': 'Ulisses',
  'vagner': 'Vagner',
  'valdeci': 'Valdeci',
  'valdemar': 'Valdemar',
  'valdir': 'Valdir',
  'valerio': 'Valério',
  'vanderlei': 'Vanderlei',
  'vicente': 'Vicente',
  'vinicius': 'Vinícius',
  'vitor': 'Vítor',
  'wagner': 'Wagner',
  'walter': 'Walter',
  'wanderley': 'Wanderley',
  'wellington': 'Wellington',
  'wilson': 'Wilson',
  'zacarias': 'Zacarias',
  
  // Sobrenomes
  'abrao': 'Abrão',
  'acacio': 'Acácio',
  'aguia': 'Águia',
  'aires': 'Aires',
  'alcantara': 'Alcântara',
  'almeida': 'Almeida',
  'alvares': 'Álvares',
  'amaral': 'Amaral',
  'andrade': 'Andrade',
  'anuncicao': 'Anunciação',
  'araujo': 'Araújo',
  'assumpcao': 'Assunção',
  'assuncao': 'Assunção',
  'ataide': 'Ataíde',
  'avila': 'Ávila',
  'azevedo': 'Azevedo',
  'baltazar': 'Baltazar',
  'barbosa': 'Barbosa',
  'barreto': 'Barreto',
  'barros': 'Barros',
  'basilio': 'Basílio',
  'batista': 'Batista',
  'beltrao': 'Beltrão',
  'benevides': 'Benevides',
  'bonfim': 'Bonfim',
  'borges': 'Borges',
  'bras': 'Brás',
  'brito': 'Brito',
  'caetano': 'Caetano',
  'camargo': 'Camargo',
  'camoes': 'Camões',
  'campos': 'Campos',
  'cardoso': 'Cardoso',
  'carrao': 'Carrão',
  'carvalho': 'Carvalho',
  'castanho': 'Castanho',
  'castro': 'Castro',
  'coelho': 'Coelho',
  'corcao': 'Corção',
  'cordeiro': 'Cordeiro',
  'correia': 'Correia',
  'correa': 'Corrêa',
  'costa': 'Costa',
  'coutinho': 'Coutinho',
  'cunha': 'Cunha',
  'dias': 'Dias',
  'duarte': 'Duarte',
  'estevao': 'Estêvão',
  'falcao': 'Falcão',
  'faria': 'Faria',
  'farias': 'Farias',
  'fernandes': 'Fernandes',
  'ferrao': 'Ferrão',
  'ferreira': 'Ferreira',
  'figueiredo': 'Figueiredo',
  'filho': 'Filho',
  'flores': 'Flores',
  'fonseca': 'Fonseca',
  'fontes': 'Fontes',
  'franca': 'França',
  'franco': 'Franco',
  'freire': 'Freire',
  'freitas': 'Freitas',
  'galvao': 'Galvão',
  'garcao': 'Garção',
  'garcia': 'Garcia',
  'godoi': 'Godói',
  'gomes': 'Gomes',
  'goncalves': 'Gonçalves',
  'guedes': 'Guedes',
  'guerra': 'Guerra',
  'guimaraes': 'Guimarães',
  'irmao': 'Irmão',
  'jesus': 'Jesus',
  'lacerda': 'Lacerda',
  'leal': 'Leal',
  'leao': 'Leão',
  'leitao': 'Leitão',
  'leite': 'Leite',
  'lemos': 'Lemos',
  'lima': 'Lima',
  'lopes': 'Lopes',
  'lourenco': 'Lourenço',
  'luz': 'Luz',
  'macedo': 'Macedo',
  'machado': 'Machado',
  'magalhaes': 'Magalhães',
  'maia': 'Maia',
  'maranhao': 'Maranhão',
  'marao': 'Marão',
  'marques': 'Marques',
  'martins': 'Martins',
  'medeiros': 'Medeiros',
  'meireles': 'Meireles',
  'melo': 'Melo',
  'mendes': 'Mendes',
  'mendonca': 'Mendonça',
  'menezes': 'Menezes',
  'miranda': 'Miranda',
  'monteiro': 'Monteiro',
  'moraes': 'Moraes',
  'moreira': 'Moreira',
  'mota': 'Mota',
  'moura': 'Moura',
  'mourao': 'Mourão',
  'munhoz': 'Munhoz',
  'muniz': 'Muniz',
  'nascimento': 'Nascimento',
  'neves': 'Neves',
  'nobrega': 'Nóbrega',
  'nogueira': 'Nogueira',
  'nunes': 'Nunes',
  'oliveira': 'Oliveira',
  'osorio': 'Osório',
  'pacheco': 'Pacheco',
  'padrao': 'Padrão',
  'paixao': 'Paixão',
  'pascoa': 'Páscoa',
  'passos': 'Passos',
  'pavao': 'Pavão',
  'pedroso': 'Pedroso',
  'peixoto': 'Peixoto',
  'penha': 'Penha',
  'pereira': 'Pereira',
  'piedade': 'Piedade',
  'pimentel': 'Pimentel',
  'pinheiro': 'Pinheiro',
  'pinto': 'Pinto',
  'pires': 'Pires',
  'proenca': 'Proença',
  'queiroz': 'Queiroz',
  'ramos': 'Ramos',
  'ramao': 'Ramão',
  'reis': 'Reis',
  'rezende': 'Rezende',
  'ribeiro': 'Ribeiro',
  'rocha': 'Rocha',
  'rodrigues': 'Rodrigues',
  'rosario': 'Rosário',
  'sa': 'Sá',
  'sales': 'Sales',
  'sampaio': 'Sampaio',
  'santana': 'Santana',
  'santiago': 'Santiago',
  'santos': 'Santos',
  'sao': 'São',
  'silva': 'Silva',
  'silveira': 'Silveira',
  'simoes': 'Simões',
  'soares': 'Soares',
  'souza': 'Souza',
  'tavares': 'Tavares',
  'teixeira': 'Teixeira',
  'toledo': 'Toledo',
  'trindade': 'Trindade',
  'vargas': 'Vargas',
  'vasconcelos': 'Vasconcelos',
  'veiga': 'Veiga',
  'verissimo': 'Veríssimo',
  'vianna': 'Vianna',
  'viana': 'Viana',
  'vieira': 'Vieira',
  'xavier': 'Xavier',
};

// Remove acentos de uma string
export function removeAccents(str: string): string {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

// Verifica se uma palavra tem correção de acento disponível
export function getAccentCorrection(word: string): string | null {
  const normalized = removeAccents(word.toLowerCase());
  return ACCENT_CORRECTIONS[normalized] || null;
}

// Corrige acentos em um nome completo
export function correctAccents(fullName: string): { corrected: string; hadCorrections: boolean } {
  const words = fullName.trim().split(/\s+/);
  let hadCorrections = false;
  
  const correctedWords = words.map(word => {
    // Se a palavra já tem acentos, mantém como está
    if (word !== removeAccents(word)) {
      return word;
    }
    
    const correction = getAccentCorrection(word);
    if (correction) {
      hadCorrections = true;
      return correction;
    }
    
    // Se não encontrou correção, capitaliza a primeira letra
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  });
  
  return {
    corrected: correctedWords.join(' '),
    hadCorrections,
  };
}

// Sugere correção para uma palavra específica
export function suggestCorrection(word: string): { original: string; suggestion: string } | null {
  if (!word || word.length < 2) return null;
  
  const correction = getAccentCorrection(word);
  if (correction && correction.toLowerCase() !== word.toLowerCase()) {
    return {
      original: word,
      suggestion: correction,
    };
  }
  
  return null;
}

// Verifica se uma string contém acentos
export function hasAccents(str: string): boolean {
  return str !== removeAccents(str);
}
